mklink /J "..\..\SpartanUI_Artwork" .\Artwork
mklink /J "..\..\SpartanUI_FilmEffects" .\FilmEffects
mklink /J "..\..\SpartanUI_PartyFrames" .\PartyFrames
mklink /J "..\..\SpartanUI_PlayerFrames" .\PlayerFrames
mklink /J "..\..\SpartanUI_RaidFrames" .\RaidFrames
mklink /J "..\..\SpartanUI_SpinCam" .\SpinCam
mklink /J "..\..\SpartanUI_Style_Fel" .\Style_Fel
mklink /J "..\..\SpartanUI_Style_Grid" .\Style_Grid
mklink /J "..\..\SpartanUI_Style_Minimal" .\Style_Minimal
mklink /J "..\..\SpartanUI_Style_Transparent" .\Style_Transparent
mklink /J "..\..\SpartanUI_Style_War" .\Style_War
mklink /J "..\..\SpartanUI_Style_Blizzard" .\Style_Blizzard