language: minimal

addons:
  apt:
    packages:
    - luarocks

install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"

    
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g 8.0.1

notifications:
  email:
    on_failure: always
    on_success: always